nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:3000']
        allow_credentials: true
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['OPTIONS', 'GET', 'POST', 'PUT', 'DELETE']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/': ~